landing/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),
]

todo/urls.py
from django.urls import path
from .views import index, AboutView, task, add_task, login_user, logout_user, register_user, delete_task

app_name = 'todo'

urlpatterns = [
    path('', index, name='index'),
    path('about/', AboutView.as_view(), name="about"),
    path('task/<int:id>', task, name="task"),
    path('add_task', add_task, name='add_task'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('register', register_user, name='register'),
    path('delete_task', delete_task, name='delete')
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todo/", include("todo.urls")),
    path("landing/", include("landing.urls"))
]

landing/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ForeignKey

# Create your models here.

class TaskModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    priority = models.IntegerField()

todo/forms.py
from django import forms

class TaskForm(forms.Form):
    task = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Add a new item...'}),
        label=''
    )
    description = forms.CharField(
        max_length=200,
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Describe task...', 'rows': 3}),
        label=''
    )
    priority = forms.ChoiceField(
        choices=[('1', 'Priority 1'), ('2', 'Priority 2'), ('3', 'Priority 3')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        label=''
    )

landing/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return HttpResponse("<h1>Landing page!</h1>")

todo/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from .forms import TaskForm
from .models import TaskModel
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
import json

# Create your views here.

# def get_task_by_id(tasks,task_id):
#     for task in tasks:
#         if task["id"] == task_id:
#             return task
#     return None

@login_required(login_url='todo:login')
def index(request):
    task_form = TaskForm()
    # print(request.session["tasks"])
    tasks = TaskModel.objects.filter(user=request.user)
    ctx = {"tasks": tasks, "form": task_form, "user": request.user }
    return render(request, "todo/index.html", ctx)

def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print(form)
        if form.is_valid():            
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('todo:index'))
    
    return render(request, 'todo/register.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('todo:index')) 
        else:
            return render(request, 'todo/login.html')

    return render(request, 'todo/login.html')

@login_required()
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('todo:index')) 

def delete_task(request):
    if request.method == 'POST':
        body = json.loads(request.body)
        task_id = body['taskId']
        task = TaskModel.objects.get(id=task_id)
        task.delete()
        return HttpResponseRedirect(reverse('todo:index'))
    
    return HttpResponseRedirect(reverse('todo:index'))

def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = TaskModel(
                user=request.user,
                name=form.cleaned_data['task'],
                description=form.cleaned_data['description'],
                priority=int(form.cleaned_data['priority']),)
            task.save()
    return HttpResponseRedirect(reverse('todo:index'))

def task(request, id):
    task = TaskModel.objects.get(id=id)
    ctx = {"task": task}
    return render(request, "todo/task.html", ctx)

class AboutView(View):
    def get(self, request):
        return HttpResponse("this is about page")

todo/templates/todo/index.html
{% extends 'todo/layout.html' %}

{% block content %}
<a href="{% url 'todo:logout' %}">Logout</a>
<h1>What will you do today, {{ user }} ?</h1>
<div class="input-container">
    <form method="POST" action="{% url 'todo:add_task' %}">
        {% csrf_token %}
        {{ form }}
        <button id="addBtn" class="btn btn-primary ">Add</button>
    </form>
</div>
<div id="lists-container" class="mt-4">
    <div id="lists-container" class="mt-4">
        <ul id="list-1" class="task-list list-group">
            <h4>Priority 1</h4>
            {% for task in tasks %}
                {% if task.priority == 1 %}
                    <li><input type="checkbox" id="{{ task.id }}" class="form-check-input"><span class="task-text">{{ task.name }}</span></li>
                {% endif %}
            {% endfor %}
        </ul>
        <ul id="list-2" class="task-list list-group">
            <h4>Priority 2</h4>
            {% for task in tasks %}
                {% if task.priority == 2 %}
                    <li><input type="checkbox" id="{{ task.id }}" class="form-check-input"><span class="task-text">{{ task.name }}</span></li>
                {% endif %}
            {% endfor %}
        </ul>
        <ul id="list-3" class="task-list list-group">
            <h4>Priority 3</h4>
            {% for task in tasks %}
                {% if task.priority == 3 %}
                    <li><input type="checkbox" id="{{ task.id }}" class="form-check-input"><span class="task-text">{{ task.name }}</span></li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    
</div>
{% endblock %}

todo/templates/todo/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Dev-Do</title>
    <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
</head>
<body>
    <div class="app-container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'todo/app.js' %}"></script>
</body>
</html>

todo/templates/todo/login.html
{% extends 'todo/layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        <!-- Add your form fields and submit button here -->
        <input type="text" name="username" placeholder="Username"><br>
        <input type="password" name="password" placeholder="Password"><br>
        <button type="submit">Login</button>
    </form>
    <p>New here? <a href="{% url 'todo:register' %}">Register here</a></p>
{% endblock %}

todo/templates/todo/register.html
{% extends 'todo/layout.html' %}

{% block content %}
<h1>Register</h1>
<form method="post" action="{% url 'todo:register' %}">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>
    <input type="password" name="password1" placeholder="Password"><br>
    <input type="password" name="password2" placeholder="Password"><br>
    <button type="submit">Register</button>
</form>
{% endblock %}

todo/templates/todo/task.html
{% extends 'todo/layout.html' %}

{% block content %}
<h1> {{ task.name }} </h1>
<p> {{ task.description }}</p>
{% endblock %}